version: '3.7'

services:
  postgres:
    image: postgres:12.14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    networks:
      red:
        ipv4_address: 10.5.0.4

  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: pgadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      red:
        ipv4_address: 10.5.0.5

networks:
  red:
    name: red
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24

volumes:
    pgadmin: