version: '3.7'

services:
  jupyter:
    build: ./jupyter
    container_name: jupyter
    restart: unless-stopped
    ports:
      - "8083:8888"
    entrypoint:
      jupyter lab --ip='0.0.0.0' --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    volumes: 
      - ./jupyter:/app
    env_file: 
      - ./jupyter/variables.env
    networks:
      red:
        ipv4_address: 10.5.0.4

  postgresql:
    image: "postgres:14"
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: itguymichal
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      red:
        ipv4_address: 10.5.0.5

networks:
  red:
    name: red
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24

volumes:
  db-data:
  pgadmin-data: