version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    volumes:
      - ./config/mysql.cnf:/etc/mysql/my.cnf
      - ./mysql:/var/lib/mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      red:
        ipv4_address: 10.5.0.2
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: default
    cap_add:
      - SYS_NICE

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: phpmyadmin
    networks:
      red:
        ipv4_address: 10.5.0.3
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
    volumes:
      - ./config/php.ini:/usr/local/etc/php/php.ini

networks:
  red:
    name: red
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
